### ISSUE TITLE
Also store copies of the CSVs in this repo for backup purposes

### ISSUE THREAD

**Issue by henare** [openaustralia/australian_local_councillors_popolo#95]
While importing some contributions I just noticed that it was quite hard to spot an unintentional error and fix it using the Sheets revision history. Maybe storing copies of the CSVs we download would help?

**Comment by equivalentideas** [comment]
As part of https://github.com/openaustralia/planningalerts/issues/1203#issuecomment-330197776 @hisayohorie and I agreed we need to get the CSV's into the repo. Read more up on that issue about the process we're imaging.

> noticed that it was quite hard to spot an unintentional error and fix it using the Sheets revision histor

This should be much easier with git diffs and the ability to `git checkout` to a specific clean slate.

So we're imaging following the pattern used by EveryPolitician of having a folder for each data folder, a folder for each jurisdiction, and then the csv and json in there. See https://github.com/everypolitician/everypolitician-data/tree/master/data/Australia/Representatives

So we're imaging a directory structure like:

- data
  - NSW
     - nsw_local_councillors.csv
     - nsw_local_councillor_popolo.csv
  - VIC
    - ...


Steps (separate PRs):

1. [ ] add the directory structure and adapt the rake task to work with it

2. [ ] download the CSV files, name them appropriately and put them into the repo

3. [ ] adapt the rake file to target the local CSV file rather than the Google Doc
      * [ ] update the docs to explain that you need to edit these files now not the Google Sheet

**Comment by equivalentideas** [comment]
I've assigned this to you @hisayohorie post any questions or anything here 😄

**Comment by equivalentideas** [comment]
@hisayohorie is doing steps 1. " add the directory structure and adapt the rake task to work with it" and 3. "adapt the rake file to target the local CSV file rather than the Google Doc" in one go in #125

**Comment by equivalentideas** [comment]
This is now done in #125
